name: test-conda-env-py3
channels:
- isuruf/label/pocl
- conda-forge
- nodefaults
dependencies:
- git
- scipy
- conda-forge::numpy
- conda-forge::sympy
- pocl
- islpy
- pyopencl
- python=3
- python-symengine=0.6.0
- pyfmmlib
- cython
- gmsh

# https://gitlab.tiker.net/inducer/pytential/-/issues/146
- compilers
