name: CI
on:
    push:
        branches:
        - master
    pull_request:
        paths-ignore:
        - 'doc/*.rst'
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    flake8:
        name: Flake8
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
                . ./prepare-and-run-flake8.sh ./pytential ./test

    pylint:
        name: Pylint
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                set -e
                CONDA_ENVIRONMENT=.test-conda-env-py3-pylint.yml
                cp .test-conda-env-py3.yml $CONDA_ENVIRONMENT
                echo "- matplotlib" >> $CONDA_ENVIRONMENT
                echo "-------------------------------------------"
                cat $CONDA_ENVIRONMENT
                echo "-------------------------------------------"
                USE_CONDA_BUILD=1
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-pylint.sh

                # Pylint won't find the Cython bits without this
                PROJECT_INSTALL_FLAGS="--editable"

                . ./prepare-and-run-pylint.sh pytential test/test_*.py

    pytest3:
        name: Pytest Linux
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: "Main Script"
            run: |
                grep -v symengine .test-conda-env-py3.yml > .test-conda-env.yml
                CONDA_ENVIRONMENT=.test-conda-env.yml
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
                . ./build-and-test-py-project-within-miniconda.sh

    pytest3mac:
        name: Pytest Mac
        runs-on: macos-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: "Main Script"
            run: |
                export LC_ALL=en_US.UTF-8
                export LANG=en_US.UTF-8
                export CONDA_ENVIRONMENT=.test-conda-env-py3-macos.yml
                export PYTEST_ADDOPTS=${PYTEST_ADDOPTS:--k-slowtest}
                export CC=clang
                # https://stackoverflow.com/q/60934005; https://reviews.llvm.org/D71579
                export LDFLAGS="-mlinker-version=519"
                set -o xtrace
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
                . ./build-and-test-py-project-within-miniconda.sh

    pytest3symengine:
        name: Pytest on Py3 with SymEngine
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: "Main Script"
            run: |
                set -e
                CONDA_ENVIRONMENT=.test-conda-env-py3.yml
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
                . ./build-and-test-py-project-within-miniconda.sh

# vim: sw=4

